CLUSTER_ENV: dev
BARNETRYGD_KONTANTSTOTTE_FEED_URL: https://familie-baks-infotrygd-feed.intern.dev.nav.no
SYKEPENGER_FEED_URL: https://vedtaksfeed.intern.dev.nav.no
STS_DISCOVERY_URL: https://security-token-service.nais.preprod.local/rest/v1/sts/.well-known/openid-configuration
STS_URL: https://security-token-service.nais.preprod.local/rest/v1/sts/token
