application:
  name: infotrygd-feed-proxy
server:
  servlet:
    context-path: /api
  port: 8087
  shutdown: graceful

no.nav.security.jwt:
  issuer:
    sts:
      discovery-url: ${STS_DISCOVERY_URL}
      accepted-audience: ${GYLDIGE_SERVICE_BRUKERE}
    azuread:
      discovery-url: ${AZURE_APP_WELL_KNOWN_URL}
      accepted-audience: ${AZURE_APP_CLIENT_ID}
      proxyurl: http://webproxy-nais.nav.no:8088
  client:
    registration:
      familie-baks-infotrygd-feed:
        resource-url: ${BAKS_FEED_URL}
        token-endpoint-url: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
        grant-type: client_credentials
        scope: api://${CLUSTER_ENV}-gcp.teamfamilie.familie-baks-infotrygd-feed/.default
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic
      vedtaksfeed:
        resource-url: ${SYKEPENGER_FEED_URL}
        token-endpoint-url: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
        grant-type: client_credentials
        scope: api://${CLUSTER_ENV}-gcp.tbd.vedtaksfeed/.default
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic
      yrkesskade:
        resource-url: ${YRKESSKADE_FEED_URL}
        token-endpoint-url: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
        grant-type: client_credentials
        scope: api://${CLUSTER_ENV}-gcp.yrkesskade.yrkesskade-infotrygd-feed/.default
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic
      foreldrepenger:
        resource-url: ${FPSAK_FEED_URL}
        token-endpoint-url: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
        grant-type: client_credentials
        scope: api://${CLUSTER_ENV}-fss.teamforeldrepenger.fpsak/.default
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic
      inst2:
        resource-url: ${INST2_URL}
        token-endpoint-url: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
        grant-type: client_credentials
        scope: api://${CLUSTER_ENV}-fss.team-rocket.${INST2_ENV}/.default
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic
      gsak:
        resource-url: ${GSAK_URL}
        token-endpoint-url: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
        grant-type: client_credentials
        scope: api://${CLUSTER_ENV}-fss.oppgavehandtering.${GSAK_ENV}/.default
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic

spring:
  autoconfigure.exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
  main:
    allow-bean-definition-overriding: true
    banner-mode: "off"

management:
  endpoint.health.show-details: never
  endpoint.health.probes.enabled: true
  endpoints.web:
    exposure.include: info, health, metrics, prometheus, env, configprops, beans

springdoc:
  packagesToScan: no.nav.infotrygd.feed.proxy
  pathsToMatch: /v3/api-docs,/**
  swagger-ui:
    disable-swagger-default-url: true

GYLDIGE_SERVICE_BRUKERE: srvinfotrygd-feed-proxy-v2, srvInfot
