application:
  name: infotrygd-feed-proxy
server:
  servlet:
    context-path: /
  port: 8087
  shutdown: graceful

no.nav.security.jwt:
  issuer:
    azuread:
      discoveryurl: ${AZURE_APP_WELL_KNOWN_URL}
      accepted_audience: ${AZURE_APP_CLIENT_ID}
      proxyurl: http://webproxy-nais.nav.no:8088
      cookie_name: azure_token
    sts:
      discoveryurl: ${STS_DISCOVERY_URL}
      accepted_audience: ${GYLDIGE_SERVICE_BRUKERE}
  client:
    registration:
      familie-baks-infotrygd-feed:
        resource-url: ${BAKS_INFOTRYGD_FEED_URL}
        token-endpoint-url: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
        grant-type: client_credentials
        scope: api://${CLUSTER_ENV}-gcp.teamfamilie.familie-baks-infotrygd-feed/.default
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic
      vedtaksfeed:
        resource-url: ${VEDTAKSFEED_URL}
        token-endpoint-url: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
        grant-type: client_credentials
        scope: api://${CLUSTER_ENV}-gcp.tbd.vedtaksfeed/.default
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic

spring:
  autoconfigure.exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
  main:
    allow-bean-definition-overriding: true
    banner-mode: "off"

management:
  endpoint.health.show-details: always
  endpoint.health.probes.enabled: true
  endpoints.web:
    exposure.include: info, health, metrics, prometheus
    base-path: "/internal"
  metrics.export.prometheus.enabled: true
  metrics.web.server.request.autotime.enabled: true

springdoc:
  packagesToScan: no.nav.infotrygd.feed.proxy
  pathsToMatch: /v3/api-docs,/api/**
  swagger-ui:
    disable-swagger-default-url: true

CLUSTER_ENV: prod
BAKS_INFOTRYGD_FEED_URL: https://familie-baks-infotrygd-feed.intern.nav.no
VEDTAKSFEED_URL: https://vedtaksfeed.intern.nav.no

STS_PREFIX: http://security-token-service.default
STS_DISCOVERY_SUFFIX: /rest/v1/sts/.well-known/openid-configuration
STS_URL: ${STS_PREFIX}/rest/v1/sts/token # Trenges av RestTemplateSTS
GYLDIGE_SERVICE_BRUKERE: srvinfotrygd-feed-proxy-v2, srvInfot
STS_DISCOVERY_URL: https://security-token-service.nais.adeo.no/rest/v1/sts/.well-known/openid-configuration
