apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: infotrygd-feed-proxy-v2
  namespace: infotrygd
  labels:
    team: infotrygd
spec:
  image: {{image}}
  port: 8087
  liveness:
    path: /api/actuator/health/liveness
    initialDelay: 30
    failureThreshold: 10
  readiness:
    path: /api/actuator/health/readiness
    initialDelay: 30
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /api/actuator/prometheus
  replicas:
    min: 2
    max: 3
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: 256Mi
      cpu: 500m
    requests:
      memory: 256Mi
      cpu: 500m
  secureLogs:
    enabled: true
  ingresses:
    - https://infotrygd-feed-proxy-v2.dev.intern.nav.no
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/dev/srvinfotrygd-feed-proxy-v2
        mountPath: /var/run/secrets/nais.io/serviceuser
  azure:
    application:
      enabled: true
      claims:
        extra:
          - azp_name
  accessPolicy:
    inbound:
      rules:
        - application: infotrygd-feed-konsument
          namespace: infotrygd
          cluster: dev-fss
    outbound:
      rules:
        - application: familie-baks-infotrygd-feed
          namespace: teamfamilie
          cluster: dev-gcp
        - application: vedtaksfeed
          namespace: tbd
          cluster: dev-gcp
        - application: yrkesskade-infotrygd-feed
          namespace: yrkesskade
          cluster: dev-gcp
        - application: fpsak
          namespace: teamforeldrepenger
          cluster: dev-fss
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: dev